# Generated by Django 3.0.1 on 2020-02-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_remove_churchinfo_license_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='alternative_phone',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='church_name',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='regno',
        ),
        migrations.RemoveField(
            model_name='churchinfo',
            name='web',
        ),
    ]
