# Generated by Django 3.0.1 on 2020-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20200212_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='itunes_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='spotify_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
